// SPDX-License-Identifier: BSL-1.1
// Copyright (c) 2026 DeadlyVirusIn

// When a provider can't be onboarded in the current shell (non-TTY, sudo
// needed, etc.), emit a portable continuation script the user can run in
// a real terminal. The script contains everything the engine would have
// done, with one provider per labeled block.

import { mkdir, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import path from 'node:path';
import type { ProviderEntry } from '../types.js';

export interface DeferredItem {
  readonly providerId: string;
  readonly displayName: string;
  readonly entry: ProviderEntry;
  readonly reasons: ReadonlyArray<string>;
}

function quoteSingle(s: string): string {
  // Safe single-quote escape: terminate, insert '\'', resume.
  return `'${s.replace(/'/g, "'\\''")}'`;
}

function blockFor(item: DeferredItem): string {
  const e = item.entry;
  const lines: string[] = [];
  lines.push('echo');
  lines.push(`echo ${quoteSingle(`──── ${item.displayName} ────`)}`);
  for (const reason of item.reasons) {
    lines.push(`echo ${quoteSingle(`  (deferred: ${reason})`)}`);
  }
  if (e.install) {
    lines.push(`echo ${quoteSingle('Install:')}`);
    lines.push(`echo ${quoteSingle(`  ${e.install.command}`)}`);
    lines.push(`${e.install.command}`);
  }
  if (e.auth) {
    switch (e.auth.flavor) {
      case 'oauth-browser':
      case 'oauth-device-code':
        if (e.auth.command) {
          lines.push(`echo ${quoteSingle('Sign in:')}`);
          lines.push(`echo ${quoteSingle(`  ${e.auth.command}`)}`);
          lines.push(`${e.auth.command}`);
        }
        break;
      case 'api-key-paste':
        if (e.auth.keyIssueUrl && e.auth.keyDestination) {
          lines.push(`echo ${quoteSingle(`Issue a key at: ${e.auth.keyIssueUrl}`)}`);
          lines.push(
            `echo ${quoteSingle(`Then write it to ~/${e.auth.keyDestination.homeRelativePath} as:`)}`,
          );
          lines.push(`echo ${quoteSingle(`  ${e.auth.keyDestination.envVarName}=<your-key>`)}`);
        }
        break;
      case 'manual-only':
        for (const s of e.auth.manualSteps ?? []) {
          lines.push(`echo ${quoteSingle(`  - ${s}`)}`);
        }
        break;
    }
  }
  if (e.postInstall) {
    lines.push(`echo ${quoteSingle(`Optional: ${e.postInstall.description}`)}`);
    lines.push(`echo ${quoteSingle(`  ${e.postInstall.command}`)}`);
  }
  return lines.join('\n');
}

export interface EmitDeferredScriptOptions {
  readonly scriptDir?: string;
  readonly filename?: string;
}

export async function emitDeferredScript(
  items: ReadonlyArray<DeferredItem>,
  opts: EmitDeferredScriptOptions = {},
): Promise<string> {
  const dir = opts.scriptDir ?? path.join(homedir(), '.manthan');
  await mkdir(dir, { recursive: true });
  const file = path.join(dir, opts.filename ?? 'setup-continue.sh');
  const header = [
    '#!/usr/bin/env bash',
    '# Generated by `manthan setup` to continue provider setup in a real terminal.',
    '# Run this in your normal shell (not inside an embedded non-TTY shell).',
    'set -e',
    '',
  ].join('\n');
  const body = items.map(blockFor).join('\n\n');
  const footer = ['', 'echo', 'echo "All deferred steps complete. Run: manthan doctor"', ''].join(
    '\n',
  );
  await writeFile(file, `${header}${body}${footer}`, { mode: 0o755 });
  return file;
}
